name: Prepare release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (without leading 'v')"
        required: true
        type: string
      name:
        description: "Release name"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  make_release_commit:
    name: Render changelog with towncrier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install towncrier
        run: python -m pip install --upgrade towncrier

      - name: Run towncrier
        run: |
          towncrier build --version ${{ inputs.version }} --yes

      - name: Configure Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Commit Changelog
        run: |
          git commit -m "Render changelog for v${{ inputs.version }}"

      - name: Tag release
        run: git tag -a "v${{ inputs.version }}" -m "v${{ inputs.version }}"

      - name: Push
        run: git push --follow-tags

      - name: Create GitHub Release
        uses: actions/github-script@v7
        id: create-release
        with:
          script: |
            return await octokit.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "v${{ inputs.version }}",
              name: "v${{ inputs.version }}"
            });
